use_frameworks!

target 'EHPageItemsView_Example' do
  pod 'EHPageItemsView', :path => '../'
  pod 'Masonry', '~> 0.6.4'
  pod 'YYCategories', '~> 1.0.1'

  target 'EHPageItemsView_Tests' do
    inherit! :search_paths

    
  end
end
